# Site settings
title: Emelianov Sergey
email: karagabul@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog of full web-developer. Posts maybe about solutions
  or examples works. Some times you find somthing funny :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://emelianov.site"
github_username:  totaki

# Build settings
markdown: kramdown
permalink: /:categories/:title
highlighter: pygments
