version: '2'

services:
  app:
    build:
      context: ./
    image: gtpages:0.3
    command: bundle exec jekyll serve --host 0.0.0.0
    container_name: emelianov_site
    volumes:
      - ./:/app/src
    network_mode: host