version: '2'

services:
  app:
    build:
      context: ./
    image: gtpages:0.1
    command: bundle exec jekyll serve --host 0.0.0.0
    container_name: emelianov_site
    volumes:
      - ./:/app/src
    ports:
      - "4000:4000"

networks:
  default:
    external:
      name: docker-compose    
